### PR TITLE
Update aqbanking.json

### PR DESCRIPTION
**Pull request by cristarta**
Fixed url path

### CODE REVIEW

**Comment by fellen** [comment]
Thanks for heads up! But I wonder if we should

1. update to a newer version; @jralls there seem to be a few fixes for macos (currently 1_2_30) and windows (currently 1.2.29) included.

1. switch to the github repo like for macos and windows?

**Comment by jralls** [comment]
@fellen, we should test the latest release (1.2.32) and if it works upgrade all three platforms to it. I think it would perhaps be better to switch to a tarball for mac and win, it will get rid of the `refusing to switch a dirty tree` error when rebuilding.

**Comment by fellen** [comment]
> I think it would perhaps be better to switch to a tarball for mac and win, it will get rid of the `refusing to switch a dirty tree` error when rebuilding.

I used "url": "https://github.com/lsh123/xmlsec/archive/refs/tags/xmlsec-1_2_32.tar.gz" for flatpak. I will leave win and mac for you.

**Comment by jralls** [comment]
OK. Did you build and test AQBanking with the updated xmlsec?

**Comment by fellen** [comment]
> OK. Did you build and test AQBanking with the updated xmlsec?

It had build fine, but i have still no configured account to test it completely.

**Comment by jralls** [comment]
> It had build fine, but i have still no configured account to test it completely.

It seems to be used only in aqebics, so I don't have any way to test it either. Oh well.

gnucash-on-osx and gnucash-on-windows updated to 1.2.32 too, so closing.

**Pull request closed without merging**
