### PR TITLE
Update Boost to 1.78.0

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by jralls** [comment]
Why?

**Comment by fellen** [comment]
> Why?

Why not? They try to ship recent software at Flathub—or do you expect problems on one of the other platforms?

**Comment by jralls** [comment]
Boost isn't part of flathub's distribuition, we're building it ourselves for our own use. The minimum version in CMakeLists.txt is 1.55. Nothing is gained by using anything newer, while there is some risk that the latest release introduces bugs or API changes that might affect GnuCash.

**Comment by travier** [comment]
This is part of an effort I'm working on to keep dependencies updated across all applications on Flathub. Feel free to hold on merging if you think this is not ready for you yet. I would however suggest that you decide on a timeline when you will be ready to update those dependencies.

**Comment by jralls** [comment]
ISTM you can find much better uses for your time.
The current boost here is only 9 months old and is 1 rev newer than what your employer ships in the just-released Fedora 35. Moreover most Boost libraries, including the ones we're using, aren't exactly a hotbed of activity, which is why we can safely specify a 9-year-old minimum version.

**Comment by travier** [comment]
Let's clarify a few things:
- This is a *personal* effort to improve dependency updates for applications on Flathub. This is a common concern regarding Flatpak application maintenance.
- The Fedora project is a community project sponsored by Red Hat. I don't see how the version shipped in Fedora has anything to do with what's used in a Flatpak where you can ship any version you prefer.
- Raising the minimum version is an unrelated change and I'm not suggesting you do that. I'm only suggesting planning for the version bump.

Why close this now when you will most likely update this library at some point later in the future?

**Comment by fellen** [comment]
From my POV, now after the release is a good moment to update all dependencies. Then they are tested in the nightlies over 2 month before the next release.

**Comment by jralls** [comment]
@travier, you miss the point, perhaps deliberately: It's that Boost 1.76 *is* reasonably up to date; only a few bleeding-edge distributions like Arch Linux are distributing 1.77 or 1.78; most are distributing [older versions](https://repology.org/project/boost/versions).

Why close this? To discourage you from continuing your project, at least with respect to GnuCash. Maybe other projects want their dependencies to be bleeding-edge. We tell ordinary non-techie users to use flathub GnuCash and we emphatically *don't* want to inflict bleeding-edge releases on them. Techie users who want bleeding edge can run Arch Linux.

@fellen I don't think that there's enough users of the nightlies for that to be useful. Better to let the Linux distros like Fedora and Debian with their multi-step integration branches do the integration testing.

**Pull request closed without merging**
